### ISSUE TITLE
Internal Error on attempt to reinforce block

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#61]
2012-09-27 15:37:32 [SEVERE] [Citadel] 
2012-09-27 15:37:32 [SEVERE] [Citadel] Internal error!
2012-09-27 15:37:32 [SEVERE] [Citadel] Include the following into your bug report:
2012-09-27 15:37:32 [SEVERE] [Citadel]           ======= SNIP HERE =======
2012-09-27 15:37:32 [SEVERE] [Citadel] java.lang.NullPointerException
2012-09-27 15:37:32 [SEVERE] [Citadel]  at com.untamedears.citadel.dao.CitadelCachingDao.getCacheOfBlock(CitadelCachingDao.java:32)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at com.untamedears.citadel.dao.CitadelCachingDao.findReinforcement(CitadelCachingDao.java:63)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at com.untamedears.citadel.ReinforcementStorage.findReinforcement(ReinforcementStorage.java:33)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at com.untamedears.citadel.ReinforcementManager.getReinforcement(ReinforcementManager.java:30)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at com.untamedears.citadel.access.AccessDelegate.getReinforcement(AccessDelegate.java:64)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at com.untamedears.citadel.listener.PlayerListener.interact(PlayerListener.java:119)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at java.lang.reflect.Method.invoke(Method.java:616)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at net.minecraft.server.ItemInWorldManager.interact(ItemInWorldManager.java:355)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:650)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at net.minecraftserverhook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:94)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at net.minecraft.server.Packet15Place.handle(SourceFile:58)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at net.minecraft.server.ServerConnection.b(SourceFile:35)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:578)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
2012-09-27 15:37:32 [SEVERE] [Citadel]  at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
2012-09-27 15:37:32 [SEVERE] [Citadel]           ======= SNIP HERE =======
2012-09-27 15:37:32 [SEVERE] [Citadel]

**Comment by remyroy** [comment]
I will have a look at this one.

**Comment by remyroy** [comment]
It's always better to call something by its name when you see it. So I'll do it here.

The cache enabling patch is a piece of shit in my humble opinion. I would just scrap it and start over. The author did it without even testing it which is insane, but it was included in the source with the label "not tested" which is even more insane.

I've tried to patch it here and there but I could not even remotely managed to make it work.

Caching is a complex problem. Java does not make it easier. I believe using an existing, well known, popular and proved solution like [Ehcache](http://ehcache.org/) from start would have been easier.

I will not be working on this anymore. If someone else wants to try, be my guest.

**Comment by JonnyD** [comment]
The problem wasn't only that it was not tested but that the pull request was accepted. Fair play to the guy for trying but since software development is a human/team activity shit happens so this is why we need some proper procedures in place.

**Comment by ttk2** [comment]
Exultant has some interesting and similar ideas, but ultimately all of the
good solutions require re-coding, Chx was our original Citadel programmer
and I knew the pull request for ram caching would probably end badly but I
wanted to try and force the hand of development and get it working or die
trying, as we either need to optimize with what we have now or start again
from the bottom. If we end up having to start again then lets be honest 
with ourselves and do it right.

**Comment by ttk2** [comment]
In all seriousness lets get this out there and discuss what to do. 

In my opinion the only next step available for Citadel is optimization, there are no other major feature requests or needs other than significant optimization. If the way the existing patch works is beyond saving I will yell at Chx and we can get on with our lives by merging changes from an older branch to overwrite Chx's changes. But from what I hear reagrdless of who codes it ram caching in the current system is going to be messy regardless of who does it or how well tested it is. 

Exultant has been talking about [Redis](http://redis.io/) for a few months now as a possible solution, since Redis holds the whole DB in ram and can be configured to write snapshots to the disk regularly (independtly of hte actions of the Minecraft server) we could avoid handling ram cahcing ourselves entierly. Of course other options are available and thats why we really need to start talking about them. 

I am sorry, I may have overstepped my bounds in merging pull requests and closing issues on this project, but the point is rapidly approching where Citadel will be totally incapable of dealing with the loads we have in mind, no matter what these issues will be solved, its just a matter of how bad do we let it get before we act. 

Thank you all very much for your time and work on this project.

**Comment by JonnyD** [comment]
I don't have time to code at the moment being back at college, in my final year and it's tough. But I understand the existing plugin inside-out so if anyone has any questions they can get in touch with me: contact@jonnydevine.com

**Comment by ttk2** [comment]
I just started my freshmen year, my schedule is not grueling but its not a cakewalk either. I think we are all trying to adjust to that, I do expect productivity to start spiking around holidays and summer though. Thanks for all your help, enjoy playing if you have to chose that over development with your free time.

**Comment by remyroy** [comment]
Here are the steps to optimization:
1. Get it right.
2. Test it's right.
3. Profile if slow.
4. Optimise (the main bottleneck only).
5. Repeat from 2. 

From my point of view, you guys are at step 4 but you forgot step 3. The NoLagg report I've seen in Issue #58 was interesting but it did not contain enough information. I have not seen a profiling report showing that Mysql was a bottleneck. We might be wasting our effort in optimizing the database queries by adding a caching layer. The bottleneck might be somewhere else. My point is we do not know. Optimizing something we do not know is a bottleneck is inefficient to say the least. Profiling is the step that will tell us what is the bottleneck. We need to know how many times each methods are called, how much CPU time each methods consumed and what percentage of the whole application time was spent in each methods.

So I think we are at step 3. I think you guys have seen that the server perform slowly at some point and it is in need of profiling. I suggest we use [VisualVM](http://visualvm.java.net/). It is a free profiling tool that is included with the JDK, that is pretty standard and well known. The feature that I like from this tool is that you can save an application profiling run into a single application snapshot which can be later processed offline. You could run the profiling tool for an hour or so on the main server in a peak, save the profiling run and we could have a look at it offline. From there, we could start optimizing.

**Comment by ttk2** [comment]
I have the VisualVM, but I want to wait until after advertising to start tinkering with somthing I am not really familar with on the live server, downtime normally is bad, downtime today may be unacceptable. Should have a report in a coupld of days though.
