### ISSUE TITLE
Constant stack trace in console

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#7]
Seems to have no ill effects on server performance or plugin operation, but makes administration from the console impossible. 

2012-03-12 14:37:09 [SEVERE] Could not pass event PlayerInteractEvent to Citadel
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:441)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:168)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:138)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:974)
    at lishid.orebfuscator.hook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:127)
    at net.minecraft.server.Packet18ArmAnimation.handle(SourceFile:38)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:116)
    at lishid.orebfuscator.hook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:60)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:554)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.NullPointerException
    at invalid.cxschx.citadel.BlockListener.controlAccess(BlockListener.java:167)
    at sun.reflect.GeneratedMethodAccessor251.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
    ... 14 more

**Comment by ttk2** [comment]
Resolved by Fnordsoft
