### ISSUE TITLE
Optimistic lock exception 

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#79]
05:31:31 [SEVERE] [Citadel] Internal error!
05:31:31 [SEVERE] [Citadel] Include the following into your bug report:
05:31:31 [SEVERE] [Citadel]           ======= SNIP HERE =======
05:31:31 [SEVERE] [Citadel] javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[delete from reinforcement where x=? and y=? and z=? and world=? and
 material_id=? and durability=? and security_level=? and name=?] bind[null]
05:31:31 [SEVERE] [Citadel]     at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.checkRowCount(DmlHandler.java:123)
05:31:31 [SEVERE] [Citadel]     at com.avaje.ebeaninternal.server.persist.dml.DeleteHandler.execute(DeleteHandler.java:81)
05:31:31 [SEVERE] [Citadel]     at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:105)
05:31:31 [SEVERE] [Citadel]     at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.delete(DmlBeanPersister.java:67)
05:31:31 [SEVERE] [Citadel]     at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeDeleteBean(DefaultPersistExecute.java:128)
05:31:31 [SEVERE] [Citadel]     at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:535)
05:31:31 [SEVERE] [Citadel]     at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:557)
05:31:31 [SEVERE] [Citadel]     at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:654)
05:31:31 [SEVERE] [Citadel]     at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:464)
05:31:31 [SEVERE] [Citadel]     at com.avaje.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1860)
05:31:31 [SEVERE] [Citadel]     at com.avaje.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1845)
05:31:31 [SEVERE] [Citadel]     at com.untamedears.citadel.dao.CitadelCachingDao$ChunkCache.flush(CitadelCachingDao.java:212)
05:31:31 [SEVERE] [Citadel]     at com.untamedears.citadel.dao.CitadelCachingDao.getCacheOfBlock(CitadelCachingDao.java:48)
05:31:31 [SEVERE] [Citadel]     at com.untamedears.citadel.dao.CitadelCachingDao.findReinforcement(CitadelCachingDao.java:71)
05:31:31 [SEVERE] [Citadel]     at com.untamedears.citadel.ReinforcementStorage.findReinforcement(ReinforcementStorage.java:33)
05:31:31 [SEVERE] [Citadel]     at com.untamedears.citadel.ReinforcementManager.getReinforcement(ReinforcementManager.java:30)
05:31:31 [SEVERE] [Citadel]     at com.untamedears.citadel.access.ChestAccessDelegate.shouldDelegate(ChestAccessDelegate.java:24)
05:31:31 [SEVERE] [Citadel]     at com.untamedears.citadel.access.AccessDelegate.<init>(AccessDelegate.java:49)
05:31:31 [SEVERE] [Citadel]     at com.untamedears.citadel.access.ChestAccessDelegate.<init>(ChestAccessDelegate.java:19)
05:31:31 [SEVERE] [Citadel]     at com.untamedears.citadel.access.AccessDelegate.getDelegate(AccessDelegate.java:27)
05:31:31 [SEVERE] [Citadel]     at com.untamedears.citadel.listener.PlayerListener.interact(PlayerListener.java:118)
05:31:31 [SEVERE] [Citadel]     at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
05:31:31 [SEVERE] [Citadel]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:31:31 [SEVERE] [Citadel]     at java.lang.reflect.Method.invoke(Method.java:601)
05:31:31 [SEVERE] [Citadel]     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
05:31:31 [SEVERE] [Citadel]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
05:31:31 [SEVERE] [Citadel]     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
05:31:31 [SEVERE] [Citadel]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:467)
05:31:31 [SEVERE] [Citadel]     at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
05:31:31 [SEVERE] [Citadel]     at net.minecraft.server.ItemInWorldManager.interact(ItemInWorldManager.java:302)
05:31:31 [SEVERE] [Citadel]     at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:647)
05:31:31 [SEVERE] [Citadel]     at net.minecraft.serverhook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:119)
05:31:31 [SEVERE] [Citadel]     at net.minecraft.server.Packet15Place.handle(SourceFile:39)
05:31:31 [SEVERE] [Citadel]     at net.minecraft.server.NetworkManager.b(NetworkManager.java:234)
05:31:31 [SEVERE] [Citadel]     at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:119)
05:31:31 [SEVERE] [Citadel]     at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:83)
05:31:31 [SEVERE] [Citadel]     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:579)
05:31:31 [SEVERE] [Citadel]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
05:31:31 [SEVERE] [Citadel]     at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
05:31:31 [SEVERE] [Citadel]           ======= SNIP HERE =======

**Comment by ttk2** [comment]
This error was shortly followed by

05:33:05 [SEVERE] Could not pass event EntityChangeBlockEvent to Citadel
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:467)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:428)
        at net.minecraft.server.PathfinderGoalEatTile.e(PathfinderGoalEatTile.java:67)
        at net.minecraft.server.PathfinderGoalSelector.a(PathfinderGoalSelector.java:74)
        at net.minecraft.server.EntityLiving.z_(EntityLiving.java:1287)
        at net.minecraft.server.EntitySheep.z_(EntitySheep.java:44)
        at net.minecraft.server.EntityLiving.e(EntityLiving.java:1165)
        at net.minecraft.server.EntityAgeable.e(EntityAgeable.java:36)
        at net.minecraft.server.EntityAnimal.e(SourceFile:30)
        at net.minecraft.server.EntitySheep.e(EntitySheep.java:52)
        at net.minecraft.server.EntityLiving.F_(EntityLiving.java:456)
        at net.minecraft.server.World.entityJoinedWorld(World.java:1286)
        at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:111)
        at net.minecraft.server.World.playerJoinedWorld(World.java:1268)
        at net.minecraft.server.World.tickEntities(World.java:1164)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:569)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[Duplicate entry '121-186-952-world' for key 'PRIMARY']
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:116)
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:76)
        at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:91)
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:527)
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:557)
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:404)
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaInsert(DefaultPersister.java:377)
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:361)
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308)
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282)
        at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1765)
        at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1751)
        at com.untamedears.citadel.dao.CitadelCachingDao$ChunkCache.flush(CitadelCachingDao.java:211)
        at com.untamedears.citadel.dao.CitadelCachingDao.getCacheOfBlock(CitadelCachingDao.java:48)
        at com.untamedears.citadel.dao.CitadelCachingDao.findReinforcement(CitadelCachingDao.java:71)
        at com.untamedears.citadel.ReinforcementStorage.findReinforcement(ReinforcementStorage.java:33)
        at com.untamedears.citadel.ReinforcementManager.getReinforcement(ReinforcementManager.java:30)
        at com.untamedears.citadel.access.AccessDelegate.getReinforcement(AccessDelegate.java:64)
        at com.untamedears.citadel.Utility.maybeReinforcementDamaged(Utility.java:137)
        at com.untamedears.citadel.listener.EntityListener.changeBlock(EntityListener.java:56)
        at sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by ttk2** [comment]
Ok I am getting these during regular operation now.

**Comment by uncorr** [comment]
Will take a look after work.  Would like to know why get CacheOfBlock is
causing a flush...

...as for the null errors in ebeanserver, those can probably be avoided
with empty checks in the save function.

**Comment by ttk2** [comment]
I think I have Erocs on it.

**Comment by erocs** [comment]
This should be closed.
